---
- name: Wait for SSH to become available
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 120
      vars:
        ansible_connection: local

- name: Install Docker
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Enable and start docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: ec2-user
        groups: docker
        append: true

    - name: Reconnect to server
      ansible.builtin.meta: reset_connection

- name: Install Docker Compose
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Downloading needed package
      shell: sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose

    - name: Fixing permissions for the package
      file:
        path: /usr/local/bin/docker-compose
        mode: +x

- name: Configure application on host
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Copy docker-compose.yaml file to host
      copy:
        src: ./files/docker-compose.yml
        dest: /home/ec2-user

    - name: Set up correct IP for frontend app so it can communicate with API # By changing line "- REACT_APP_API_HOST=http://127.0.0.1:5050" in docker-compose.yaml file
      lineinfile:
        path: /home/ec2-user/docker-compose.yml
        regexp: "- REACT_APP_API_HOST=http://127.0.0.1:5050"
        line: "     - REACT_APP_API_HOST=http://{{ ec2_ip }}:5050"

    - name: Set up unsplash.com account # By changing line "- UNSPLASH_KEY=pass_key_here" in docker-compose.yaml file
      lineinfile:
        path: /home/ec2-user/docker-compose.yml
        regexp: "- UNSPLASH_KEY=pass_key_here"
        line: "     - UNSPLASH_KEY={{ unsplash_key }}"

    - name: Pull images and start containers # docker-compose module supports docker compose version <2.0. So it will be not working in our case.
      shell: "cd /home/ec2-user/ && docker-compose up -d"
